#cloud-config

package_update: true
package_upgrade: true

users:
  - name: devops
    groups: sudo
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ${SSH_PUBLIC_KEY}

runcmd:
  - apt-get install -y git
  - mkdir -p /opt/bootstrap
  - git clone https://github.com/simeonprimordial/automated-linux-server-bootstrap.git /opt/bootstrap
  - chmod +x /opt/bootstrap/scripts/bootstrap.sh
  - /opt/bootstrap/scripts/bootstrap.sh
  - /opt/bootstrap/scripts/verify.sh > /var/log/bootstrap-verification.log 2>&1